### ISSUE TITLE
Missing source in PP and PC triggers test failure in admiral PR test

### ISSUE THREAD

**Issue by RealSlimMahdi** [pharmaverse/admiraltest#27]
<img width="793" alt="CleanShot 2022-04-07 at 18 17 37@2x" src="https://user-images.githubusercontent.com/36238571/162250098-e507d349-610e-4b61-8325-1232dc8b5133.png">

**Comment by RealSlimMahdi** [comment]
There are others files with the same issue, do you think to change the test, or should we enforce a source parameter ?

**Comment by rossfarrugia** [comment]
Closing as now merged to main
