### ISSUE TITLE
Rename datasets

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiraltest#30]
All datasets should be renamed such that they include the `admiral_` prefix in their name, e.g. `dm` should be changed to `admiral_dm`.

**Comment by sophie-gem** [comment]
Unless there are any first contributors who would like to do this (as I don't want to take this opportunity away from other prospective contributors), I'd be happy to take this on. Let me know 😃

**Comment by thomas-neitmann** [comment]
Feel free to go ahead @sophie-gem 🙂

**Comment by sophie-gem** [comment]
Cool great - thanks @thomas-neitmann! Should I also go through and update the references in admiral?

**Comment by thomas-neitmann** [comment]
That would be much appreciated!

**Comment by thomas-neitmann** [comment]
Please create a new issue for that in admiral once you're done with this update.

**Comment by sophie-gem** [comment]
Cool ok - will do 🙂

**Comment by sophie-gem** [comment]
scripts and files that need updating as a result:

- [ ] R/get_terms.R (? - unsure on this one, need to look into further)
- [ ] R/data.R
- [ ] data_scripts/pc.R
- [ ] data_scripts/pp.R
- [ ] data_scripts/query_databases.R
- [ ] data_scripts/rs.R
- [ ] data_scripts/tr.R
- [ ] data_scripts/tu.R

data_scripts ones are probably not vital - but thought I'd update (to save them to data/admiral_<xx>.rda) for completeness.

**Comment by sophie-gem** [comment]
I have left R/get_terms.R as is - don't believe this needs updating.

**Comment by sophie-gem** [comment]
Hi @thomas-neitmann, currently I have renamed the .rda datasets - however when I load these using `data("admiral_ae")` for example - it is accessible from the environment as `ae` rather than `admiral_ae`. Would you like me to alter this so the variable name is also `admiral_ae`?

**Comment by sophie-gem** [comment]
I can do this by doing something along the lines of:
```
new_env <- new.env()
data("admiral_cm", envir = new_env)

admiral_cm <- new_env$cm
save(admiral_cm, file = "data/admiral_cm.rda", compress = "bzip2")
```
This then means that when you do `data('admiral_cm')` the dataset loaded has the variable name `admiral_cm`.

**Comment by thomas-neitmann** [comment]
Yes, the variables names should also have the `admiral_` prefix.

**Comment by sophie-gem** [comment]
Great, thanks @thomas-neitmann! I will make these changes now.

**Comment by sophie-gem** [comment]
Let me know if you would like the code which I used to do this as reference somewhere.

**Comment by rossfarrugia** [comment]
Closing as now merged to main
