### ISSUE TITLE
`R/get_terms.R` needs data references updated

### ISSUE THREAD

**Issue by sophie-gem** [pharmaverse/admiraltest#32]
Code Line 16: currently `data("smq_db", envir = temp_env)` needs to become `data("admiral_smq_db", envir = temp_env)`

Code Line 54: currently `data("sdg_db", envir = temp_env)` needs to become `data("admiral_sdg_db", envir = temp_env)`

(This is one section I missed when doing this [issue](https://github.com/pharmaverse/admiraltest/issues/30))

**Comment by rossfarrugia** [comment]
Closing as now merged to main
