### ISSUE TITLE
CRAN Submission Feedback

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiraltest#39]
> Dear maintainer,

> package admiraltest_0.2.0.tar.gz has been auto-processed and is pending a manual inspection. A CRAN team member will typically respond to you within the next 5 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

> Log dir: <https://win-builder.r-project.org/incoming_pretest/admiraltest_0.2.0_20220520_140216/>
The files will be removed after roughly 7 days.
Installation time in seconds: 38
Check time in seconds: 189
R Under development (unstable) (2022-05-19 r82383 ucrt)

> Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/admiraltest_0.2.0_20220520_140216/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/admiraltest_0.2.0_20220520_140216/Debian/00check.log>
Status: 1 NOTE

> No strong reverse dependencies to be checked.

> Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NOTE
  Maintainer: 'Thomas Neitmann <[thomas.neitmann@roche.com](mailto:thomas.neitmann@roche.com)>'

>   New submission

>   Possibly misspelled words in DESCRIPTION:
    ADaM (20:41)
    CDISC (19:44)
    SDTM (18:52)

>   Found the following (possibly) invalid URLs:
    URL: https://bitbucket-test.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/sv.xpt
      From: man/admiral_sv.Rd
      Status: Error
      Message: Failed to connect to [bitbucket-test.cdisc.org](http://bitbucket-test.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse
      From: README.md
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/ae.xpt
      From: man/admiral_ae.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/cm.xpt
      From: man/admiral_cm.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/dm.xpt
      From: man/admiral_dm.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/ds.xpt
      From: man/admiral_ds.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/ex.xpt
      From: man/admiral_ex.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/lb.xpt
      From: man/admiral_lb.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/mh.xpt
      From: man/admiral_mh.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/qs.xpt
      From: man/admiral_qs.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/suppae.xpt
      From: man/admiral_suppae.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/suppdm.xpt
      From: man/admiral_suppdm.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/suppds.xpt
      From: man/admiral_suppds.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/ts.xpt
      From: man/admiral_ts.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/vs.xpt
      From: man/admiral_vs.Rd
      Status: Error
      Message: Failed to connect to [bitbucket.cdisc.org](http://bitbucket.cdisc.org/) port 443: Timed out
    URL: https://github.com/pharmaverse/admiral.test/blob/main/data/pc.rda (moved to https://github.com/pharmaverse/admiraltest/blob/main/data/pc.rda)
      From: man/admiral_pc.Rd
            man/admiral_pp.Rd
      Status: 404
      Message: Not Found

**Comment by rossfarrugia** [comment]
Closing as now merged to main
